baseURL               = "https://sixingwang2025.github.io/Tangent-nav/"
languageCode          = "zh-CN"
title                 = "Tangent导航"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"


[params]
    author        = "PaleTangent"
    description   = "Tangent 网址导航 | SITES BY PaleTangent | Hugo 主题 BY Bio IT 爱好者"
    upload        = "https://www.yuque.com/forms/share/1a1fee15-f7a9-4ee6-9dd4-b0ba9fef1871"
    about         = "https://github.com/shenweiyan/Knowledge-Garden/discussions/10"
    repository    = "https://github.com/sixingwang2025/Tangent-nav"
    enablePreLoad = true
    textPreLoad   = "Tangent 网址导航"
    expandSidebar = false
    logosPath     = "assets/images/logos"
    defaultLogo   = "assets/images/logos/default.webp"
    nightMode     = false
    yiyan         = true
    fancybox      = true

[params.seo]
    baiduhmid       = 'efccc04cb44fc49faddac5876180b369'
    baiduSiteVer    = 'codeva-cCAOSG8MBO'
    tj51laid        = ''
    tj51lack        = ''
    GoogleAdsClient = ''

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/favicon_head.png"
    searchImageL      = "assets/images/bg-bright.png"
    searchImageD      = "assets/images/bg-bright.png"
    logoExpandLight   = "assets/images/Tangent-expand-light.png"
    logoExpandDark    = "assets/images/Tangent-expand-dark.png"
    logoCollapseLight = "assets/images/Tangent.png"
    logoCollapseDark  = "assets/images/Tangent.png"

[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：PaleTangent@163.com <br/>&copy; 2021 - {year} By [WebStack-Hugo](https://github.com/shenweiyan/WebStack-Hugo) | [PaleTangent](https://sixingwang2025.github.io/) <br/>'
