name: Hugo Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
         submodules: true
         fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.122.0'
          extended: false

      - name: Build Site
        run: |
          cp -R exampleSite/* .
          ln -s $(pwd) ../WebStack-Hugo
          hugo --themesDir ../ --baseURL https://sixingwang2025.github.io/Tangent-nav/

      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: sixingwang2025/Tangent-nav
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          full_commit_message: ${{ github.event.head_commit.message }}
